# Generated by Django 5.1.5 on 2026-02-23 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("failed", "Failed"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="idx_job_status_created"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScrapedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_html",
                    models.CharField(help_text="S3 object reference", max_length=1024),
                ),
                ("cleaned_text", models.TextField()),
                (
                    "detected_language",
                    models.CharField(default="unknown", max_length=32),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scraped_content",
                        to="ingestion.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SummaryResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary_text", models.TextField()),
                ("model_name", models.CharField(max_length=128)),
                ("prompt_version", models.CharField(max_length=64)),
                ("temperature", models.FloatField(default=0.2)),
                ("token_usage", models.PositiveIntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="ingestion.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TranslationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translated_text", models.TextField()),
                ("translation_engine", models.CharField(max_length=128)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="ingestion.job",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stage", models.CharField(max_length=64)),
                ("detail", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="ingestion.job",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["job", "stage", "created_at"],
                        name="idx_job_audit_stage",
                    )
                ],
            },
        ),
    ]
